from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.experimentstool, name='experimentstool'),
    url(r'^_get_new_stock$',
        views.get_new_stock, name='_get_new_stock'),
    url(r'^_upload_application$',
        views.upload_application, name='_upload_application'),
    url(r'^_load_applications$',
        views.load_applications, name='_load_applications'),
    url(r'^_load_owned_applications$',
        views.load_owned_applications, name='_load_owned_applications'),
    url(r'^_get_application_inputs$',
        views.get_application_inputs, name='_get_application_inputs'),
    url(r'^_get_datasets$',
        views.get_datasets, name='_get_datasets'),
    url(r'^_get_dataset_info$',
        views.get_dataset_info, name='_get_dataset_info'),
    url(r'^_deploy_application$',
        views.create_deployment, name='_deploy_application'),
    url(r'^_get_deployments$',
        views.get_deployments, name='_get_deployments'),
    url(r'^_get_executions$',
        views.get_executions, name='_get_executions'),
    url(r'^_execute_deployment$',
        views.execute_deployment, name='_execute_deployment'),
    url(r'^_get_executions_events$',
        views.get_executions_events, name='_get_executions_events'),
    url(r'^_destroy_deployment$',
        views.destroy_deployment, name='_destroy_deployment'),
    url(r'^_remove_application$',
        views.remove_application, name='_remove_application'),
    url(r'^_get_hpc_list$',
        views.get_hpc_list, name='_get_hpc_list'),
    url(r'^_add_hpc$',
        views.add_hpc, name='_add_hpc'),
    url(r'^_delete_hpc$',
        views.delete_hpc, name='_delete_hpc'),
    url(r'^_get_tunnel_list$',
        views.get_tunnel_list, name='_get_tunnel_list'),
    url(r'^_add_tunnel$',
        views.add_tunnel, name='_add_tunnel'),
    url(r'^_delete_tunnel$',
        views.delete_tunnel, name='_delete_tunnel'),
    url(r'^_get_ckan_key$',
        views.get_ckan_key, name="_get_ckan_key"),
    url(r'^_update_ckan_key$',
        views.update_ckan_key, name="_update_ckan_key"),
]
