version: '3'

services:
  web:
    build: .
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/portal/static
    expose:
      - 8000
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=db
      - SQL_PORT=5432
      - MARKETPLACE_URL=${MARKETPLACE_URL}
      - DATACATALOGUE_URL=${DATACATALOGUE_URL}
      - ORCHESTRATOR_HOST=${ORCHESTRATOR_HOST}
      - ORCHESTRATOR_USER=${ORCHESTRATOR_USER}
      - ORCHESTRATOR_PASS=${ORCHESTRATOR_PASS}
      - ORCHESTRATOR_TENANT=${ORCHESTRATOR_TENANT}
      - FIWARE_IDM_ENDPOINT=${FIWARE_IDM_ENDPOINT}
      - SOCIAL_AUTH_FIWARE_KEY=${SOCIAL_AUTH_FIWARE_KEY}
      - SOCIAL_AUTH_FIWARE_SECRET=${SOCIAL_AUTH_FIWARE_SECRET}
    depends_on:
      - db
  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
  nginx:
    image: nginx:1.15.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/portal/static
    ports:
      - ${PORT}:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
